server:
  #指定端口号
  port: 8080
spring:
  application:
    #指定应用名称
    name: HikariCP-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/hikaricptest?useSSL=false&characterEncoding=utf8
    hikari:
      #是否自动提交
      auto-commit: true
      #如果在没有任何连接可用的情况下超过此时间，则将抛出sqlexception
      connection-timeout: 30000
      #控制允许连接在池中空闲的最长时间
      idle-timeout: 600000
      #控制池中连接的最长生命周期。使用中的连接永远不会退役，只有当它关闭时才会被删除
      max-lifetime: 1800000
      #此属性控制允许池到达的最大大小，包括空闲和正在使用的连接
      maximum-pool-size: 10
      # 如果您的驱动程序支持JDBC4，强烈建议不要设置此属性
      # connection-test-query:
      # 控制HikariCP尝试在池中维护的最小空闲连接数。建议不要设置此值，而是允许HikariCP充当固定大小的连接池。 默认值：与maximumPoolSize相同
      # minimum-idle:
info:
  app:
    name: HikariCP-测试
    version: 0.0.1
